config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root 'homes#top'
  get '/home/about' => 'homes#about' 
  resources :users,only: [:show,:index,:edit,:update] do
    post '/relationships' => 'relationships#create'
    delete '/relationships' => 'relationships#destroy'
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books
  resources :book, only: [:new, :create, :index, :show] do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
# ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
    #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
    has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
    # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
    has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================
  attachment :profile_image, destroy: false

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end



  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 } 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books= Book.where(user_id: @user.id)
	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
	@users = @books.all
  end

  def index
	@books= Book.where(user_id: current_user.id)
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
	@user =current_user
	@followers = @user.followers
	@followings = @user.followings
	# @relationship= Relationship.where(follewing_id: current_user.id)
  end

  def edit
	  @user = User.find(params[:id])
	  if @user.id != current_user.id
		redirect_to user_path(current_user.id)
	  end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
	  else
		
  		render "edit"
  	end
  end

  def follows
	user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @user = user.followers
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
		  
			<th>follow</th>
			<th><%= link_to user.followings.count, follows_user_path(user) %></th>
		</tr>
		<tr>
		<th>follower</th>
		<th><%= link_to user.followers.count, followers_user_path(user) %></th>

	</tr>
</table>
<% if current_user != user %>
<% if user.followed_by?(current_user) %>
	<p><%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-warning" %></p>
<% else %>
	<p><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info" %></p>
	<% end %>
<% end %>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :title %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/followers.html.erb
<h2>Followes Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
<% @user.each do |user| %>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
        <td><%= user.name%></td>
        <td> 
        <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-warning" %></p>
        <% else %>
            <p><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info" %></p>
            <% end %>
        <% end %>
        </td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォワロー数：<%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
    </tr>
    <% end %>
    </tbody>
    </table>

app/views/users/follows.html.erb
フォロー
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
<% @users.each do |user| %>
    <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
        <td><%= user.name%></td>
        <td> 
        <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-warning" %></p>
        <% else %>
            <p><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info" %></p>
            <% end %>
        <% end %>
    </td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォワロー数：<%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
    </tr>
    <% end %>
    </tbody>
    </table>

app/views/users/index.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user, followings: @followings, followers: @followers %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td> 
			<% if current_user != user %>
			<% if user.followed_by?(current_user) %>
				<p><%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-warning" %></p>
			<% else %>
				<p><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info" %></p>
			    <% end %>
		    <% end %>
		</td>
			<td>フォロー数：<%= user.followings.count %></td>
			<td>フォワロー数：<%= user.followers.count %></td>
			<td><%= link_to "Show", user_path(user) %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-xs-3">
   <h2>User info</h2>
<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	</div>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<td>
			<div class="comment-list bt style-2" id="comments">
			<div class="float-wrapper">
				<p class="comment-count">コメント数：<%= book.book_comments.count %></p>
			</div>
		  </td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div> 
<!--books一覧 -->