config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root 'homes#top'
  get '/home/about' => 'homes#about' 
  resources :users,only: [:show,:index,:edit,:update] do
    post '/relationships' => 'relationships#create'
    delete '/relationships' => 'relationships#destroy'
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books
  resources :book, only: [:new, :create, :index, :show] do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  
  
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
  def show
	  @book = Book.find(params[:id])
	  @user= @book.user 
	  @book_comment = BookComment.new
  end

  def index
  	  @books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
	  @book = Book.new
	  @user= current_user
    end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
	  @book.user_id = current_user.id
   if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book.id), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
	  @book = Book.find(params[:id])
	  if @book.user_id != current_user.id
		redirect_to books_path
	  end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to book_path(@book.id), notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end



  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(@book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
    <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
<h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
  <ul>
	<% @book.errors.full_messages.each do |message| %>
	  <li><%= message %></li>
	<% end %>
  </ul>
  
</div>
<% end %>

<div class="row">
	<div class="col-xs-3">
      
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', user: @user, book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
					<% if book.favorited_by?(current_user) %>
					<li>
					  <%= link_to book_favorites_path(book), method: :delete do %>
						<i class="glyphicon glyphicon-heart", aria-hidden="true" ></i>
						<%= book.favorites.count %>
					  <% end %>
					</li>
				  <% else %>
					<li>
					  <%= link_to book_favorites_path(book), method: :post do %>
						<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
						<%= book.favorites.count %> 
					  <% end %>
					</li>
				  <% end %>
				  </td>
                  <td>
				  <div class="comment-list bt style-2" id="comments">
					<div class="float-wrapper">
						<p class="comment-count">コメント数：<%= book.book_comments.count %></p>
					</div>
				  </td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->

</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform' %>

	</div>
    
	<div class="col-xs-9">
	<% if @book_comment.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
    <h2><%= @book_comment.errors.count %>errors prohibited this book from being saved:</h2>
  <ul>
	<% @book_comment.errors.full_messages.each do |message| %>
	  <li><%= message %></li>
	<% end %>
  </ul>
  
</div>
<% end %>
		<h2>Book detail</h2>

		<table class="table table-inserve">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<td>
					<% if @book.favorited_by?(current_user) %>
					
					  <%= link_to book_favorites_path(@book), method: :delete do %>
						<i class="glyphicon glyphicon-heart", aria-hidden="true" ></i>
						<%= @book.favorites.count %>
					  <% end %>
				
				  <% else %>
			
					  <%= link_to book_favorites_path(@book), method: :post do %>
						<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
						<%= @book.favorites.count %> 
					  <% end %>
			
				  <% end %>
				  </td>
                 <td>
				<div class="comment-list bt style-2" id="comments">
					<div class="float-wrapper">
						<p class="comment-count">コメント数：<%= @book.book_comments.count %></p>
					</div>
				  </td>
					<% if current_user.id == @book.user.id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				    <% end %>
					</tr>
			</table>
			<table>
			<h2>User Comment</h2>
			<% @book.book_comments.each do |book_comment| %>
			   <tr>
				 <td>
				 <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
				 <%= book_comment.user.name %>
				 </td>
				 <td><%= book_comment.created_at.strftime('%Y/%m/%d') %></td>
				 <td><%= book_comment.comment %></td>
				 <% if current_user.id == book_comment.user.id %>
				 <td><td><%= link_to "Destroy",book_book_comments_path(book_comment.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td></td>
			     <% end %>
				 </tr>
			<% end %>
            </table>
			<%= form_for [@book, @book_comment] do |f| %>
				<div class="row">
					<div class="col-sm-12">
						<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに入力" %>
					</div>
				</div>
				<%= f.submit "送信する", class: "btn btn-info btn-base-1 mt-20 pull-right" %>
			<% end %>
	</div>
</div>
</div>